apiVersion:  v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
#  for the non secret configs
#  mongodb-service is actulally the url or ip address of the database. which was creatd in mongodb-deployment.yml
  database-url: mongodb-service