apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: database-dashboard

spec:
  replicas: 2
  selector:
    matchLabels:
      app: database-dashboard
  template:
    metadata:
      labels:
        app: database-dashboard
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-express-secret
                  key: password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database-url

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service

spec:
  selector:
    app: database-dashboard
  #  type load balancer means this service is an external srvice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081 # own port
      targetPort: 8081 # target container port

      #  port to exposet the service to other pods or outer world (while not using ingress)
      nodePort: 30000
