apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-database
  labels:
    app: database

spec:
  replicas: 2
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password

--- 

apiVersion: v1
kind: Service
metadata: 
  name: mongodb-service

spec: 
  selector:
    app: database
  ports: 
    - protocol: TCP
      port: 27017
      targetPort: 27017
      